# Generated by Django 5.1.6 on 2025-03-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Overdue', 'Overdue'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
