# Generated by Django 5.1.6 on 2025-03-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Overdue', 'Overdue'), ('Completed', 'Completed')], default='Pending', editable=False, max_length=20),
        ),
    ]
